# Generated by Django 5.0.2 on 2024-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=15)),
                ('Apellidos', models.CharField(max_length=15)),
                ('Edad', models.IntegerField()),
            ],
        ),
    ]
